version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12.22.9
  pre_build:
    commands:
      - npm ci
  build:
    commands:
      - npm test

reports:
  jest_reports:
    files:
      - reports
    file-format: JUNITXML
    base-directory: test-result.xml
  coverage-report:
    files:
      - 'coverage/clover.xml'
    file-format: 'CLOVERXML'